version: "2"
services:
  front:
    build: dwf-fe
    restart: always
    ports:
      - "3000:3000"
    links:
      - back
  back:
    build: dwf-be
    restart: always
    ports:
      - "9000:9000"
    links:
      - db
  db:
    build: dwf-db
    env_file:
      - db_auth.env
    ports:
      - "8080:5432"
    restart: always
